package com.epam.reports.entities;

import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Trainings_Duration")
public class TrainingSummary {
	
	@DynamoDBHashKey(attributeName = "trainerUsername")
	private String trainerUsername;
	
	@DynamoDBAttribute(attributeName = "trainerFirstName")
	private String trainerFirstName;

	@DynamoDBAttribute(attributeName = "trainerLastName")
	private String trainerLastName;
	
	@DynamoDBAttribute(attributeName = "status")
	private String status;

	@DynamoDBAttribute(attributeName = "years")
    private List<Year> years;
	
	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	@DynamoDBDocument
	public static class Year{
		
		private int yearNumber;
		
		@DynamoDBAttribute(attributeName = "months")
        private List<Month> months;}
	
	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	@DynamoDBDocument
	public static class Month{
		
		private String name;
		
		@DynamoDBAttribute(attributeName = "trainingSummaryDuration")
        private List<TrainingSummaryDuration> trainingSummaryDuration;
	}
	
	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	@DynamoDBDocument 
	public static class TrainingSummaryDuration{
		
		private String trainingName;
		private double duration;
	}

	
		
	
//	public List<String> getMonthsByYear(Integer year){
//		return this.years.stream()
//				.filter(y->y.getYearNumber()==year)
//				.findFirst()
//				.map(n->n.getMonths())
//				.map(m->m.stream()
//						.map(n->n.getName())
//						.toList()).orElse(List.of());
//	}
//	public List<String> getTrainingsByYearAndMonth(Integer year,String month){
//		return this.years.stream()
//                .filter(y -> y.getYearNumber()==year)
//                .findFirst()
//                .map(Year::getMonths)
//                .map(months -> months.stream()  
//                                   .filter(m -> m.getName().equals(month))
//                                   .findFirst()
//                                   .map(Month::getTrainingSummaryDuration)
//                                   .map(TrainingSummaryDuration::getTrainingName)
//                					.stream())
//                .orElseGet(Stream::empty)
//                .toList();
//	}
	
}








